global class UpdateProportionateforNonScheme {
    /*
    @InvocableMethod(label='Convert Leads')
    global static List<ConvertLeadActionResult> convertLeads(List<ConvertLeadActionRequest> requests) {
        for (ConvertLeadActionRequest request:requests){
        string newDescription = requests[0].Description.replace('N',String.valueOf(request.Count));
         string regex = '\\*';
        String PayLineTime= newDescription.replaceFirst(regex,String.valueOf(request.TimeLinkedCount));
        }
        
        return ConvertLeadActionRequest;
        
    }

    global class ConvertLeadActionRequest {
       @InvocableVariable
        global string Description;
        @InvocableVariable
        global integer TimeLinkedCount;
        @InvocableVariable
        global integer Count;
        @InvocableVariable
        global string PayLineTime;
       
        
    }*/

}