@isTest
public class TestTeamMember {
    /*@isTest
     public static Project__c createProject() {
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        insert p;
        return p;
    }
     
    @isTest
    public static void CreateTeam() {
        Project__c p = createProject();
        
        Team__c tm = new Team__c();
        tm.Name = 'test2';
        tm.Project__c = p.id;
        tm.Team_Type__c = 'Presales Team';
        insert tm;
        
        
        Team_Members__c tmc = new Team_Members__c();
        tmc.Team__c = tm.id;
        tmc.Availability__c = true;
        tmc.Sequence_Number__c = 1;
        tmc.User__c = Userinfo.getUserId();
        insert tmc;
        
        teamMemberSeqHandler.teamMemberSeq(tmc);
    }*/
}